{
  imports = [
    ./fhs.nix
    ./fonts.nix
    ./hannah.nix
    ./kbd.nix
    ./man-pages.nix
    ./dbus.nix
    ./mk-fish-default.nix
    ./pipewire-graphical.nix
    ./pipewire.nix
    ./plymouth.nix
    ./ssh.nix
    ./pager.nix
    ./intel-usb-rw.nix
    ./console.nix
    ./zen-kernel.nix
    ./gaming-performance-tweaks.nix
    ./wine.nix
    ./qemu.nix
    ./sway.nix
    ./hyprland.nix
    ./hyprpaper.nix
    ./plasma.nix
    ./uwsm.nix
    ./secrets.nix
    ./qt.nix
  ];
}
